"use client";

import { useEffect, useState } from "react";
import { calculateScenario, companyData as fallbackData } from "@/lib/demo-data";

type Data = typeof fallbackData;
type View = "Overview" | "Revenue" | "Customers" | "Product" | "Forecasts" | "Scenarios" | "Alerts" | "Data sources";
const views: View[] = ["Overview", "Revenue", "Customers", "Product", "Forecasts", "Scenarios", "Alerts", "Data sources"];
const icons = ["⌂", "↗", "◎", "◇", "⌁", "◈", "△", "⊞"];
const subtitles: Record<View, string> = {
  Overview: "Here’s what’s happening across Northstar Labs today.", Revenue: "Understand recurring revenue, movement, and segment performance.",
  Customers: "Monitor customer health, renewals, and expansion potential.", Product: "Track engagement, adoption, and product-led growth signals.",
  Forecasts: "Review transparent baseline projections and the assumptions driving the plan.", Scenarios: "Model strategic decisions and compare their financial impact.",
  Alerts: "Prioritize risks and opportunities across the business.", "Data sources": "Manage the systems powering your executive intelligence layer.",
};

export default function Home() {
  const [active, setActive] = useState<View>("Overview");
  const [data, setData] = useState<Data>(fallbackData);
  const [loading, setLoading] = useState(true);
  const [brief, setBrief] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [period, setPeriod] = useState("Last 12 months");
  const [alerts, setAlerts] = useState(fallbackData.alerts);
  const [scenarioName, setScenarioName] = useState("New growth plan");
  const [price, setPrice] = useState(8);
  const [churn, setChurn] = useState(2.8);
  const [hires, setHires] = useState(6);
  const [result, setResult] = useState(calculateScenario(8, 2.8, 6));
  const [savedScenarios, setSavedScenarios] = useState(data.scenarios);
  const [scenarioBusy, setScenarioBusy] = useState(false);

  useEffect(() => { fetch("/api/company").then(r => r.ok ? r.json() : Promise.reject()).then(r => { setData(r.data); setAlerts(r.data.alerts); setSavedScenarios(r.data.scenarios); }).finally(() => setLoading(false)); }, []);
  useEffect(() => {
    fetch("/api/scenarios").then(r => r.ok ? r.json() : Promise.reject()).then(r => {
      if (r.scenarios?.length) setSavedScenarios(r.scenarios.map((s: Data["scenarios"][number]) => ({ ...s, saved: true })));
    }).catch(() => undefined);
    fetch("/api/alerts").then(r => r.ok ? r.json() : Promise.reject()).then(r => {
      const states = new Map<number, string>(r.states.map((s: {alertId:number;status:string}) => [s.alertId, s.status]));
      setAlerts(current => current.map(a => ({ ...a, resolved: states.get(a.id) === "resolved" || a.resolved })));
    }).catch(() => undefined);
  }, []);
  useEffect(() => { const timer = setTimeout(async () => { setScenarioBusy(true); try { const r = await fetch("/api/scenario", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ price, churn, hires }) }); setResult(r.ok ? await r.json() : calculateScenario(price, churn, hires)); } catch { setResult(calculateScenario(price, churn, hires)); } finally { setScenarioBusy(false); } }, 180); return () => clearTimeout(timer); }, [price, churn, hires]);

  const openAlerts = alerts.filter(a => !a.resolved).length;
  const navigate = (view: View) => { setActive(view); setQuery(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const globalResults = views.filter(v => v.toLowerCase().includes(query.toLowerCase()));
  const saveScenario = async () => {
    const optimistic = { name: scenarioName, price, churn, hires, ...result, saved: true };
    try {
      const response = await fetch("/api/scenarios", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(optimistic) });
      if (!response.ok) throw new Error("save failed");
      const payload = await response.json();
      setSavedScenarios([{ ...payload.scenario, saved: true }, ...savedScenarios]);
    } catch { setSavedScenarios([optimistic, ...savedScenarios]); }
  };

  return <main className="shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => navigate("Overview")}><b>S</b><span>SignalBoard <em>AI</em></span></button>
      <div className="workspace"><i>N</i><span><small>WORKSPACE</small><strong>{data.company.name}</strong></span><b>⌄</b></div>
      <label>COMMAND CENTER</label>
      <nav>{views.map((item, i) => <button className={active === item ? "active" : ""} onClick={() => navigate(item)} key={item}><i>{icons[i]}</i><span>{item}</span>{item === "Alerts" && openAlerts > 0 && <b>{openAlerts}</b>}</button>)}</nav>
      <div className="sidefoot"><p><i/><span><strong>{loading ? "Syncing systems…" : "All systems synced"}</strong><small>Updated {data.company.syncedAt}</small></span></p><p><b>NK</b><span><strong>Nikhil Kumar</strong><small>Administrator</small></span></p></div>
    </aside>

    <section className="content">
      <header><div><small>TUESDAY, JULY 21</small><h1>{active === "Overview" ? "Good morning, Nikhil." : active}</h1><p>{subtitles[active]}</p></div><div className="actions"><button aria-label="Search" onClick={() => setSearchOpen(true)}>⌕</button><button aria-label="Alerts" className="notification" onClick={() => navigate("Alerts")}>♢{openAlerts > 0 && <i/>}</button><button className="primary" onClick={() => setBrief(true)}>✦ Generate briefing</button></div></header>
      {active === "Overview" && <Overview data={data} period={period} setPeriod={setPeriod} navigate={navigate} brief={() => setBrief(true)}/>}
      {active === "Revenue" && <Revenue data={data}/>}
      {active === "Customers" && <Customers data={data}/>}
      {active === "Product" && <Product data={data}/>}
      {active === "Forecasts" && <Forecasts data={data} result={result}/>}
      {active === "Scenarios" && <Scenarios price={price} churn={churn} hires={hires} setPrice={setPrice} setChurn={setChurn} setHires={setHires} result={result} busy={scenarioBusy} name={scenarioName} setName={setScenarioName} saved={savedScenarios} onSave={saveScenario}/>}
      {active === "Alerts" && <Alerts alerts={alerts} setAlerts={setAlerts}/>}
      {active === "Data sources" && <Sources data={data}/>}
    </section>

    {brief && <Modal close={() => setBrief(false)}><div className="ai">✦</div><small className="kicker">AUTOMATED EXECUTIVE BRIEFING · RULE BASED</small><h2>Northstar is ahead of plan.</h2><p className="lead">Growth remains efficient, led by enterprise expansion and improving retention.</p><div className="brief"><Brief n="01" title="Revenue momentum strengthened">MRR reached $2.31M, with enterprise upgrades driving 41% of net new revenue.</Brief><Brief n="02" title="Retention is outperforming">NRR improved to 118.6% as expansion offset a modest increase in SMB churn.</Brief><Brief n="03" title="One area needs attention">Cloud compute is 12% above plan. Rightsizing could recover $21K monthly.</Brief></div><button className="save" onClick={() => setBrief(false)}>Done</button></Modal>}
    {searchOpen && <Modal close={() => setSearchOpen(false)}><h2>Go anywhere</h2><input className="search-input" autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search views…"/><div className="search-results">{globalResults.map(v => <button key={v} onClick={() => { navigate(v); setSearchOpen(false); }}>{v}<span>→</span></button>)}</div></Modal>}
  </main>;
}

function Overview({data, period, setPeriod, navigate, brief}:{data:Data;period:string;setPeriod:(v:string)=>void;navigate:(v:View)=>void;brief:()=>void}) { return <>
  <div className="intelligence"><b>✦</b><div><small>SIGNALBOARD INTELLIGENCE</small><strong>Expansion revenue is accelerating.</strong><span>Enterprise upgrades contributed $184K in new MRR this month—32% above forecast.</span></div><button onClick={brief}>View analysis →</button></div>
  <SectionTitle title="Company pulse" text="Key metrics compared to the previous period"><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 12 months</option><option>This quarter</option><option>Last 30 days</option></select></SectionTitle>
  <div className="metrics"><Metric label="ANNUAL RECURRING REVENUE" value={`$${data.kpis.arr}M`} delta="18.4%"/><Metric label="NET REVENUE RETENTION" value={`${data.kpis.nrr}%`} delta="4.2%"/><Metric label="GROSS MARGIN" value={`${data.kpis.margin}%`} delta="1.8%"/><Metric label="CASH RUNWAY" value={`${data.kpis.runway} mo`} delta="2.1 mo"/></div>
  <div className="grid"><article className="card chart-card"><CardHead kicker="REVENUE PERFORMANCE" title="Monthly recurring revenue" tag="● On track"/><div className="chart-value"><strong>$2.31M</strong><span>↑ 4.5% this month</span></div><BarChart labels={data.revenue.months} values={data.revenue.mrr}/><button className="link" onClick={()=>navigate("Revenue")}>Open revenue analytics →</button></article><article className="card"><CardHead kicker="ATTENTION REQUIRED" title="Risks & opportunities"/>{data.alerts.slice(0,3).map(a=><Signal key={a.id} alert={a}/>)}<button className="link" onClick={()=>navigate("Alerts")}>View all signals →</button></article><article className="card forecast"><CardHead kicker="BASELINE FORECAST" title="ARR trajectory" tag="Linear trend"/><div className="forecast-main"><div><small>PROJECTED ARR · DEC 2026</small><strong>$29.6M</strong><span>Disclosed baseline method</span></div><MiniBars values={data.forecast}/></div><button className="link" onClick={()=>navigate("Forecasts")}>Explore forecast →</button></article><article className="card scenario"><small>STRATEGIC PLANNING</small><h3>Model your next move</h3><p>Test pricing, hiring, and retention decisions against your growth plan.</p><div className="bubbles"><b>+8%<small>Pricing</small></b><b>2.8%<small>Churn</small></b><b>+6<small>Hires</small></b></div><button onClick={()=>navigate("Scenarios")}>Open scenario studio →</button></article></div>
  </>; }

function Revenue({data}:{data:Data}) { const [metric,setMetric]=useState<"mrr"|"newBusiness"|"expansion">("mrr"); const values=data.revenue[metric]; return <><div className="metrics three"><Metric label="MONTHLY RECURRING REVENUE" value="$2.31M" delta="4.5%"/><Metric label="NEW BUSINESS MRR" value="$468K" delta="9.1%"/><Metric label="EXPANSION MRR" value="$184K" delta="7.6%"/></div><div className="view-grid"><article className="card wide"><div className="toolbar"><CardHead kicker="REVENUE TREND" title="Recurring revenue movement"/><div className="segmented"><button className={metric==="mrr"?"active":""} onClick={()=>setMetric("mrr")}>MRR</button><button className={metric==="newBusiness"?"active":""} onClick={()=>setMetric("newBusiness")}>New</button><button className={metric==="expansion"?"active":""} onClick={()=>setMetric("expansion")}>Expansion</button></div></div><BarChart labels={data.revenue.months} values={values}/></article><article className="card"><CardHead kicker="ARR MIX" title="Revenue by segment"/>{data.segments.map(s=><div className="segment" key={s.name}><div><i style={{background:s.color}}/><strong>{s.name}</strong><span>{s.customers} customers</span></div><b>${s.arr}M</b><em>↑ {s.growth}%</em></div>)}</article></div><article className="card table-card"><CardHead kicker="MOVEMENT WATERFALL" title="Monthly revenue bridge"/><table><thead><tr><th>Month</th><th>Starting MRR</th><th>New business</th><th>Expansion</th><th>Contraction</th><th>Ending MRR</th></tr></thead><tbody>{data.revenue.months.slice(-6).map((m,i)=><tr key={m}><td><strong>{m}</strong></td><td>${(1.82+i*.08).toFixed(2)}M</td><td className="positive">+${data.revenue.newBusiness[i+6]}K</td><td className="positive">+${data.revenue.expansion[i+6]}K</td><td className="negative">-${data.revenue.contraction[i+6]}K</td><td><strong>${data.revenue.mrr[i+6]}M</strong></td></tr>)}</tbody></table></article></>; }

function Customers({data}:{data:Data}) { const [filter,setFilter]=useState("All"); const [query,setQuery]=useState(""); const rows=data.customers.filter(c=>(filter==="All"||c.status===filter)&&c.name.toLowerCase().includes(query.toLowerCase())); return <><div className="metrics"><Metric label="TOTAL CUSTOMERS" value="3,842" delta="6.2%"/><Metric label="HEALTHY ACCOUNTS" value="82.4%" delta="3.1%"/><Metric label="ARR AT RISK" value="$286K" delta="1.4%" down/><Metric label="UPCOMING RENEWALS" value="48" delta="12 this week"/></div><article className="card table-card"><div className="toolbar"><CardHead kicker="CUSTOMER PORTFOLIO" title="Account health and renewals"/><div className="table-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Healthy</option><option>At risk</option><option>Expansion</option><option>Monitor</option></select></div></div><table><thead><tr><th>Account</th><th>Plan</th><th>ARR</th><th>Health</th><th>Usage</th><th>Renewal</th><th>Status</th></tr></thead><tbody>{rows.map(c=><tr key={c.name}><td><strong>{c.name}</strong></td><td>{c.plan}</td><td>${(c.arr/1000).toFixed(0)}K</td><td><Health value={c.health}/></td><td>{c.usage}%</td><td>{c.renewal}</td><td><Status value={c.status}/></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">No customers match this filter.</div>}</article></>; }

function Product({data}:{data:Data}) { return <><div className="metrics"><Metric label="MONTHLY ACTIVE USERS" value="41,280" delta="11.2%"/><Metric label="DAU / MAU" value={`${data.usage.stickiness}%`} delta="4.8%"/><Metric label="SESSIONS PER USER" value={`${data.usage.sessions}`} delta="0.6"/><Metric label="AI ACTIONS COMPLETED" value="1.84M" delta="22.3%"/></div><div className="view-grid"><article className="card wide"><CardHead kicker="FEATURE ADOPTION" title="Usage across the product"/>{data.features.map(f=><div className="feature-row" key={f.name}><div><strong>{f.name}</strong><span>{f.wau.toLocaleString()} weekly users</span></div><div className="progress"><i style={{width:`${f.adoption}%`}}/></div><b>{f.adoption}%</b><em className={f.change<0?"negative":"positive"}>{f.change>0?"↑":"↓"} {Math.abs(f.change)}%</em></div>)}</article><article className="card"><CardHead kicker="ENGAGEMENT" title="Active user rhythm"/><div className="rings"><div className="ring"><b>{data.usage.dau.toLocaleString()}</b><small>DAU</small></div><div className="ring second"><b>{data.usage.wau.toLocaleString()}</b><small>WAU</small></div><div className="ring third"><b>{data.usage.mau.toLocaleString()}</b><small>MAU</small></div></div><div className="insight"><b>✦</b><p><strong>Copilot drives retention</strong>Teams using AI Copilot 3+ times weekly retain 18% better.</p></div></article></div></>; }

function Forecasts({data,result}:{data:Data;result:{arr:number;margin:number;runway:number}}) {
  const [model,setModel]=useState<{forecast:number[];source:string;metrics:null|{mae:number;rmse:number;mape_pct:number};limitations:string}>({forecast:data.forecast,source:"loading",metrics:null,limitations:"Loading disclosed model metadata…"});
  useEffect(()=>{fetch("/api/forecast").then(r=>r.json()).then(setModel).catch(()=>setModel(current=>({...current,source:"unavailable",limitations:"Forecast service is currently unavailable."})));},[]);
  const validation=model.metrics?`MAE ${model.metrics.mae}`:"Fallback";
  return <><div className="metrics three"><Metric label="PROJECTED MRR · +8 MO" value={`$${model.forecast.at(-1)?.toFixed(2)??"—"}M`} delta="Baseline"/><Metric label="MODEL METHOD" value="Linear" delta={model.source==="python_fastapi"?"Python API":"TS fallback"}/><Metric label="VALIDATION" value={validation} delta={model.metrics?`MAPE ${model.metrics.mape_pct}%`:"No holdout metrics"}/></div><div className="view-grid"><article className="card wide"><CardHead kicker="8-MONTH OUTLOOK" title="MRR baseline projection" tag={model.source==="python_fastapi"?"FastAPI model":"Disclosed fallback"}/><div className="forecast-chart"><MiniBars values={model.forecast}/><div className="forecast-labels">{["Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar"].map(x=><span key={x}>{x}</span>)}</div></div><p>{model.limitations}</p></article><article className="card"><CardHead kicker="MODEL DRIVERS" title="Operating assumptions"/><Driver label="Expansion momentum" value="Observed" impact="Positive" tone="positive"/><Driver label="Logo acquisition" value="Input" impact="On plan" tone="positive"/><Driver label="SMB churn" value="Observed" impact="Elevated" tone="negative"/><Driver label="Pricing uplift" value="Scenario only" impact="Excluded" tone=""/></article></div><article className="card assumption-card"><CardHead kicker="CURRENT ASSUMPTIONS" title="Operating plan inputs"/><div><span><small>AVERAGE PRICE INCREASE</small><strong>8.0%</strong></span><span><small>MONTHLY LOGO CHURN</small><strong>2.8%</strong></span><span><small>PLANNED HIRES</small><strong>6</strong></span><span><small>MODELED ARR</small><strong>${result.arr}M</strong></span></div></article></>;
}

function Scenarios({price,churn,hires,setPrice,setChurn,setHires,result,busy,name,setName,saved,onSave}:{price:number;churn:number;hires:number;setPrice:(v:number)=>void;setChurn:(v:number)=>void;setHires:(v:number)=>void;result:{arr:number;margin:number;runway:number};busy:boolean;name:string;setName:(v:string)=>void;saved:Data["scenarios"];onSave:()=>void}) { return <><div className="scenario-workbench"><article className="card controls"><CardHead kicker="SCENARIO INPUTS" title="Adjust operating assumptions"/><label className="name-field">Scenario name<input value={name} onChange={e=>setName(e.target.value)}/></label><Range label="Pricing increase" value={price} min={0} max={20} step={1} suffix="%" set={setPrice}/><Range label="Monthly churn" value={churn} min={1} max={6} step={.1} suffix="%" set={setChurn}/><Range label="New hires" value={hires} min={0} max={20} step={1} suffix="" set={setHires}/><button className="save" onClick={onSave}>Save scenario</button></article><article className="card outcome"><CardHead kicker="PROJECTED OUTCOME" title="Impact against current plan" tag={busy?"Calculating…":"Live model"}/><div className="outcome-main"><span><small>PROJECTED ARR</small><strong>${result.arr}M</strong><em>↑ ${Math.max(result.arr-24.8,0).toFixed(1)}M</em></span><span><small>GROSS MARGIN</small><strong>{result.margin}%</strong><em>vs. 76.4% today</em></span><span><small>CASH RUNWAY</small><strong>{result.runway} mo</strong><em>vs. 21.4 today</em></span></div><div className="recommendation"><b>✦</b><p><strong>SignalBoard recommendation</strong>{result.runway<18?"Growth improves, but runway falls below the 18-month operating threshold. Consider phasing hires.":"This scenario maintains a healthy runway while improving ARR and margin."}</p></div></article></div><SectionTitle title="Saved scenarios" text="Compare strategic paths side by side"/><div className="scenario-list">{saved.map((s,i)=><article className="card" key={`${s.name}-${i}`}><small>{i===0&&saved.length>3?"JUST SAVED":"SCENARIO"}</small><h3>{s.name}</h3><div><span>ARR <b>${s.arr}M</b></span><span>Margin <b>{s.margin}%</b></span><span>Runway <b>{s.runway} mo</b></span></div><p>{s.price}% pricing · {s.churn}% churn · {s.hires} hires</p></article>)}</div></>; }

function Alerts({alerts,setAlerts}:{alerts:Data["alerts"];setAlerts:(v:Data["alerts"])=>void}) { const [filter,setFilter]=useState("Open"); const rows=alerts.filter(a=>filter==="All"||(filter==="Open"?!a.resolved:a.resolved)); const resolve=async(id:number)=>{ setAlerts(alerts.map(a=>a.id===id?{...a,resolved:true}:a)); await fetch("/api/alerts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({alertId:id,status:"resolved"})}).catch(()=>undefined); }; return <><div className="alert-summary"><span><b>{alerts.filter(a=>!a.resolved).length}</b>Open signals</span><span><b>{alerts.filter(a=>a.severity==="critical"&&!a.resolved).length}</b>Critical</span><span><b>$428K</b>Revenue impact</span></div><article className="card alerts-page"><div className="toolbar"><CardHead kicker="SIGNAL INBOX" title="Risks and opportunities"/><div className="segmented">{["Open","Resolved","All"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{rows.map(a=><div className={`alert-item ${a.resolved?"resolved":""}`} key={a.id}><b className={a.severity}>{a.severity==="critical"?"!":a.severity==="opportunity"?"↗":"△"}</b><div><span>{a.type}</span><strong>{a.title}</strong><p>{a.detail}</p><small>{a.owner} · {a.time}</small></div><em>{a.impact}</em>{!a.resolved?<button onClick={()=>resolve(a.id)}>Resolve</button>:<i>✓ Resolved</i>}</div>)}</article></>; }

function Sources({data}:{data:Data}) { const [sources,setSources]=useState(data.sources); const [modal,setModal]=useState(false); const [importStatus,setImportStatus]=useState("Upload customer,mrr CSV"); const connect=(name:string)=>setSources(sources.map(s=>s.name===name?{...s,status:"Connected",sync:"Just now",records:"Sync starting"}:s)); const upload=async(file:File)=>{setImportStatus("Validating…");const form=new FormData();form.set("file",file);const r=await fetch("/api/imports",{method:"POST",body:form});const result=await r.json();setImportStatus(r.ok?`${result.import.validRows} rows · $${Number(result.metrics.mrr).toLocaleString()} MRR`:result.error);}; return <><div className="source-head"><div><h2>Connected systems</h2><p>Data is normalized into SignalBoard’s unified SaaS model.</p></div><button className="primary-button" onClick={()=>setModal(true)}>+ Add data source</button></div><article className="card pipeline"><CardHead kicker="WORKING INGESTION" title="Import subscription data"/><p>Use a CSV with <strong>customer,mrr</strong> columns. Valid rows and calculated MRR/ARR are persisted to your workspace.</p><label className="primary-button">Choose CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label><p>{importStatus}</p></article><div className="source-grid">{sources.map(s=><article className="card source-card" key={s.name}><div className="source-icon">{s.icon}</div><div><h3>{s.name}</h3><p>{s.category}</p></div><Status value={s.status}/><dl><div><dt>Records</dt><dd>{s.records}</dd></div><div><dt>Last sync</dt><dd>{s.sync}</dd></div></dl>{s.status!=="Connected"?<button onClick={()=>connect(s.name)}>Reconnect</button>:<button>Manage</button>}</article>)}</div>{modal&&<Modal close={()=>setModal(false)}><h2>Connector roadmap</h2><p>CSV ingestion is live. OAuth connectors remain intentionally labeled as planned until credentials, webhooks and field mapping are implemented.</p><div className="connector-list">{["Stripe","Salesforce","HubSpot","PostgreSQL"].map(x=><button key={x} disabled><b>{x[0]}</b>{x}<span>Planned</span></button>)}</div></Modal>}</>; }

function SectionTitle({title,text,children}:{title:string;text:string;children?:React.ReactNode}) { return <div className="section-title"><div><h2>{title}</h2><p>{text}</p></div>{children}</div>; }
function Metric({label,value,delta,down=false}:{label:string;value:string;delta:string;down?:boolean}) { return <article className="metric"><span>{label}</span><strong>{value}</strong><p className={down?"negative":""}><b>{down?"↓":"↑"} {delta}</b> vs. previous period</p><div>{[3,5,4,7,8,10,9,13,15,16].map((n,i)=><i style={{height:n}} key={i}/>)}</div></article>; }
function CardHead({kicker,title,tag}:{kicker:string;title:string;tag?:string}) { return <div className="card-head"><div><small>{kicker}</small><h3>{title}</h3></div>{tag&&<b>{tag}</b>}</div>; }
function BarChart({labels,values}:{labels:string[];values:number[]}) { const max=Math.max(...values); return <div className="chart"><div className="bars">{values.map((v,i)=><i key={i} title={`${labels[i]}: ${v}`} style={{height:`${25+(v/max)*70}%`}} className={i===values.length-1?"last":""}/>)}</div><div className="months">{labels.map(x=><span key={x}>{x}</span>)}</div></div>; }
function MiniBars({values}:{values:number[]}) { const max=Math.max(...values); return <div className="mini">{values.map((v,i)=><i key={i} className={i>values.length-3?"future":""} style={{height:`${(v/max)*100}%`}} title={`$${v}M`}/>)}</div>; }
function Signal({alert}:{alert:Data["alerts"][number]}) { return <div className="signal"><b className={alert.severity==="critical"?"red":alert.severity==="opportunity"?"green":"amber"}>{alert.severity==="critical"?"!":alert.severity==="opportunity"?"↗":"△"}</b><span><strong>{alert.title}</strong><small>{alert.detail}</small></span><em>{alert.impact}</em></div>; }
function Health({value}:{value:number}) { return <div className="health"><i style={{width:`${value}%`}}/><span>{value}</span></div>; }
function Status({value}:{value:string}) { return <span className={`status ${value.toLowerCase().replaceAll(" ","-")}`}>{value}</span>; }
function Driver({label,value,impact,tone}:{label:string;value:string;impact:string;tone:string}) { return <div className="driver"><span><strong>{label}</strong><small>{value}</small></span><b className={tone}>{impact}</b></div>; }
function Range({label,value,min,max,step,suffix,set}:{label:string;value:number;min:number;max:number;step:number;suffix:string;set:(n:number)=>void}) { return <label className="range"><span>{label}<b>{value}{suffix}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>; }
function Modal({children,close}:{children:React.ReactNode;close:()=>void}) { return <div className="backdrop" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button>{children}</section></div>; }
function Brief({n,title,children}:{n:string;title:string;children:React.ReactNode}) { return <p><b>{n}</b><span><strong>{title}</strong>{children}</span></p>; }
